# Generated by Django 5.0.4 on 2024-04-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predefined_exercise_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('major_muscle', models.CharField(max_length=50)),
                ('exercise_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='date_workout_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_date', models.DateField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='WorkoutTracker.predefined_exercise_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='WorkoutTracker.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='set_detail_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('repetition', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('date_workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='WorkoutTracker.date_workout_table')),
            ],
        ),
        migrations.CreateModel(
            name='custom_exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('major_muscle', models.CharField(max_length=50)),
                ('exercise_type', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs', to='WorkoutTracker.user_table')),
            ],
        ),
    ]
